### ISSUE TITLE
A question about distribution index $s$ in Distribution-Aware Robust Generalization

### ISSUE THREAD

**Issue by wnn2000** [zhuohuangai/SharpDRO#1]
Hi, what a really good paper! 

I just have some touble in understanding the distribution index. To my understanding, each sample $(x, y)$ has an extra label $s$, which indicates the distribution it belongs to. Samples from the same distribution (i.e., samples have the same severity of corruptions in this paper) have the same label $s$. But, we don't know the correspondence between $s$ and severity of corruptions. Therefore, we introduce $\omega$ to find the worst-case.

Is this understanding correct?

**Comment by zhuohuangai** [comment]
Thank you for your interest in our paper!

Your explanation is absolutely right. If we already know which distribution is the worst, there is no need to conduct worst-case training. However, such a situation is unrealistic due to the Poisson-distributed photon noise being a probabilistic problem. In future work, it might be helpful to model the distribution by estimating the severity of each distribution.

**Comment by wnn2000** [comment]
Fine, I have understood. Thank for your reply. 

Well, I think this paper is a really good paper that inspires me a lot. Wish you lucky in your future research.

Nannan

**Comment by zhuohuangai** [comment]
Many thanks, Nanan, really appreciate your kindness. I wish you achieve greatness in your career.
If there are any further discussions, please feel free to get in touch, hope I can help.

Sincerely, Zhuo.
